In [38]:
import pandas as pd
import numpy as np
from  sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import  MultinomialNB

import nltk
from nltk.tag import pos_tag
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from nltk.stem import PorterStemmer, WordNetLemmatizer



In [39]:
df = pd.read_csv('bbc_text_cls.csv')
df.head(5)

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [40]:
# stemming 
stemmer = PorterStemmer()
def porter_stemmer(text):
    return " ".join([stemmer.stem(x)   for x in word_tokenize(text)])

df["text"] = df["text"].apply(porter_stemmer)

In [41]:
# one_hot_encoded
CATAGORICAL_DATA = ['business', 'entertainment', 'politics', 'sport', 'tech']
def categorical_to_numberical(text):
    text =str(text).lower()
    if(text==CATAGORICAL_DATA[0]):
        return 0
    elif(text == CATAGORICAL_DATA[1]):
        return 1
    elif(text == CATAGORICAL_DATA[2]):
        return 2
    elif(text == CATAGORICAL_DATA[3]):
        return 3
    elif(text == CATAGORICAL_DATA[4]):
        return 4
    else:
        return 5
df['labels'] = df['labels'].apply(categorical_to_numberical)

In [42]:
X= df["text"]
y=df["labels"]
y
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
from nltk.corpus import stopwords
vectorizer = CountVectorizer( stop_words=stopwords.words('english'))
vectorizer.fit(X_train)
X_train= vectorizer.transform(X_train)
X_test = vectorizer.transform(X_test)



<735x17627 sparse matrix of type '<class 'numpy.int64'>'
	with 108076 stored elements in Compressed Sparse Row format>

In [54]:
nb = MultinomialNB()
nb.fit(X_train.toarray(),y_train)
pre_y = nb.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pre_y))
print(confusion_matrix(y_test,pre_y))


              precision    recall  f1-score   support

           0       0.98      0.96      0.97       185
           1       0.99      0.97      0.98       129
           2       0.96      0.98      0.97       131
           3       1.00      0.99      1.00       155
           4       0.95      0.99      0.97       135

    accuracy                           0.98       735
   macro avg       0.98      0.98      0.98       735
weighted avg       0.98      0.98      0.98       735

[[177   0   4   0   4]
 [  1 125   1   0   2]
 [  2   0 128   0   1]
 [  1   0   0 154   0]
 [  0   1   0   0 134]]


In [59]:
(X_train!=0).sum()

228060

In [45]:
# limmatizer 

def add_pos_tag(tag):
    if(tag.startswith('J')):
        return wordnet.ADJ
    elif(tag.startswith("N")):
        return wordnet.NOUN
    elif(tag.startswith("V")):
        return wordnet.VERB
    elif(tag.startswith('R')):
        return wordnet.ADV
    else:
        return wordnet.NOUN

wnl = WordNetLemmatizer()
print(wnl.lemmatize("walling",pos='v'))
# def lemmatizer_text(text):
    
#     return 

wall
